### ISSUE TITLE
Sedflux input files

### ISSUE THREAD

**Issue by juliohm** [mcflugen/sedflux#1]
Hi Eric,

I wasn't able to find the example input files: https://github.com/mcflugen/sedflux/blob/master/docs/running.txt

Could you please give some help?

**Comment by juliohm** [comment]
Alternatively, where I can learn the syntax of the input files?

**Comment by mcflugen** [comment]
I've created a new repository for sedflux input files. To get things started I threw up some input files for a sedflux simulation for Ohau, NZ. I'll add more later.

The new repository is here: https://github.com/mcflugen/sedflux-input

**Comment by juliohm** [comment]
Hi Eric,

Thank you, will check the repository soon.
